name: qe_pfas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # Materials Science & DFT
  - qe
  - ase
  - pymatgen
  - cif2cell
  - openbabel
  
  # Cheminformatics
  - rdkit
  
  # Data Science & Machine Learning
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - joblib
  - matplotlib
  
  # Database & Utilities
  - sqlalchemy
  - requests
  - reportlab
  - paramiko